# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["self@mgattozzi.dev"]
description = "Personal blog for mgattozzi"
language = "rust"
manifest_version = 2
name = "blog"
service_id = "0uLpYXzr7roaEyW0TPqgE5"

[scripts]
  build = "cargo build --bin blog --release --target wasm32-wasi --color always"
